### ISSUE TITLE
empty char array

### ISSUE THREAD

**Issue by BrunoEberhard** [leaningtech/cheerpj-meta#28]
An empty char array cannot be printed:

```
package charArray;

public class EmptyCharArray {

	public static void main(String[] args) throws Exception {
		char[] emptyCharArray = new char[0];

		System.out.println("Print char[0]");
		System.out.println("Empty Char Array: " + emptyCharArray);
		System.out.println("Done");
	}
}
```
As of latest on 27.3.2018.

regards

Bruno / minimalj.org

**Comment by alexp-sssup** [comment]
This is fixed in the current ```latest``` endpoint

**Comment by BrunoEberhard** [comment]
You're fast 👍 

The example above now works. Still not working:

```
public class EmptyCharArray {

	public static void main(String[] args) throws Exception {
		char[] emptyCharArray = new char[0];

		System.out.println("Print char[0]");
		System.out.println("Empty Char Array: " + emptyCharArray);
		System.out.println("Use equals on char[0]");
		System.out.println(Objects.equals(emptyCharArray, ""));
		System.out.println("Done");
	}
}
```

**Comment by alexp-sssup** [comment]
This other test also works with current ```latest```.

**Comment by BrunoEberhard** [comment]
Yes, works.
