### ISSUE TITLE
405 Method Not Allowed Error should be PUT but giving POST error

### ISSUE THREAD

**Issue by willishf** [leaningtech/cheerpj-meta#40]
Java code works to do a JSON PUT to a web service. Get the error message below with a single call where the POST in the error message is suspect as it should be PUT. In the Java code if I change to a POST I get a 405 error that POST not allowed. Suspecting that the Javascript code to set to PUT isn't working. The following is the Java code where confirmed that connection.setRequestMethod(request.method.name()); in the Javascript code is passing "PUT".

            URL apiUrl = new URL(uri);
            connection = (HttpURLConnection) apiUrl.openConnection();

            prepareSslConnection(connection);
            System.out.println("prepareSslConnection complete");
            System.out.println("Using connection.setRequestMethod(" + request.method.name() + ")");
            connection.setRequestMethod(request.method.name());
            System.out.println("connection.setRequest complete");
            if (request.followRedirects != null) {
                connection.setInstanceFollowRedirects(request.followRedirects);
            }
            connection.setUseCaches(request.useCaches);
            System.out.println("connection.setUseCaches complete");
            setTimeouts(request, connection);
            System.out.println("setTimeouts complete");
            if (request.ifModifiedSince != null) {
                connection.setIfModifiedSince(request.ifModifiedSince);
            }

            WebbUtils.addRequestProperties(connection, mergeHeaders(request.headers));
            System.out.println("WebbUtils.addRequestProperties complete");
            if (clazz == JSONObject.class || clazz == JSONArray.class) {
                WebbUtils.ensureRequestProperty(connection, HDR_ACCEPT, APP_JSON);
                System.out.println("WebbUtils.ensureRequestProperty complete");
            }

            if (request.method != Request.Method.GET && request.method != Request.Method.DELETE) {
                if (request.streamPayload) {
                    WebbUtils.setContentTypeAndLengthForStreaming(connection, request, request.compress);
                    connection.setDoOutput(true);
                    streamBody(connection, request.payload, request.compress);
                } else {
                    byte[] requestBody = WebbUtils.getPayloadAsBytesAndSetContentType(
                            connection, request, request.compress, jsonIndentFactor);
                    System.out.println("WebbUtils.getPayloadAsBytesAndSetContentType complete");        
                    if (requestBody != null) {
                        connection.setDoOutput(true);
                        System.out.println("connection.setDoOutput complete");
                        writeBody(connection, requestBody);
                        System.out.println("writeBody complete");
                    }
                }
            } else {
                connection.connect();
            }

            response.connection = connection;
            response.statusCode = connection.getResponseCode();
            response.responseMessage = connection.getResponseMessage();

rt.jar.com.js:512 POST http://localhost:8084/AnnotateROIServer/webresources/ImageAnnotation 405 (Method Not Allowed)
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapsoTbX0g2eHwuea2NtK7APNe9xS2MN2g @ rt.jar.com.js:512
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapogTbXKyZd1e7uebaJ3RNb9xSnItD9sya @ rt.jar.com.js:242
_h4pbSgzZHttpURLConneceWZJtBqmTsi940irW5mq496jc @ rt.jar.java.net.js:442
(anonymous) @ VM57723:4
runContinuationStack @ loader.js:374
cheerpjSchedule @ loader.js:1024
classLoadComplete @ loader.js:164
error (async)
loadScript @ loader.js:291
cheerpjLoadJarPackage @ loader.js:313
_m4VanRn3cGKuPdWarunFbsZWMJZK0ueWtrzeSNe9ZKebNxKp @ rt.jar.js:297
_m4VanRn3cGKuPdWarKnEbsZWMJZK0ueWtrzCmA0j1YINe9ZKebNxer @ rt.jar.js:324
_m4VanJm3cGKuPdabzjaMczqrpeSNe9h8mtteCEr1a @ rt.jar.js:324
_m4VanJm3cGKuPdabzjaMczqrpeSNe9h8mtteCEr1a @ rt.jar.js:324
_c4pbMxWAxsDjavJWbrKV2Zd3cGKuPdabzjaMczqrpeSNe9h8mtteCEr1a @ rt.jar.js:1776
loadWeakClass @ loader.js:339
cjG @ loader.js:2191
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqappkTbXek10d1e7uebaJ3RNb9xSnItTntza @ rt.jar.com.js:242
_c4pbQZDUHdrWs$aqfYaomrqqVveYeXMZaMNb9taRr2C400J7AjNttdHab8qS2M3l @ AnnotateModelJSON.jar.js:55
_c4pbQVDUHdrWs$aqfYaomrqa_pXfHa1eHxuFG8$kbefH00c9BCo3cGKKuQKm_kH0JtJeb @ AnnotateModelJSON.jar.js:55
_c4pbQRDUHdrWs$aqfYaomrqWoXfHa1eHxuEG8$kbefH00c9BCo3cGKKuQKm_kH0JtJeb @ AnnotateModelJSON.jar.js:55
_c4pbQFDUHdrWs$aqfYW$kbefH0epGKbXpS3RxuKKm_kH0JtJeb @ AnnotateModelJSON.jar.js:27
(anonymous) @ VM57637:3
runContinuationStack @ loader.js:374
cheerpjSchedule @ loader.js:1024
rt.jar.com.js:512 POST http://localhost:8084/AnnotateROIServer/webresources/ImageAnnotation 405 (Method Not Allowed)
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapsoTbX0g2eHwuea2NtK7APNe9xS2MN2g @ rt.jar.com.js:512
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapogTbXKyZd1e7uebaJ3RNb9xSnItD9sya @ rt.jar.com.js:242
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapogTbXuibWar0hcXYGNONe9d @ rt.jar.com.js:242
(anonymous) @ VM57735:3
runContinuationStack @ loader.js:374
cheerpjSchedule @ loader.js:1024
xhr.onload @ rt.jar.com.js:512
load (async)
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapsoTbX0g2eHwuea2NtK7APNe9xS2MN2g @ rt.jar.com.js:512
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqapogTbXKyZd1e7uebaJ3RNb9xSnItD9sya @ rt.jar.com.js:242
_h4pbSgzZHttpURLConneceWZJtBqmTsi940irW5mq496jc @ rt.jar.java.net.js:442
(anonymous) @ VM57723:4
runContinuationStack @ loader.js:374
cheerpjSchedule @ loader.js:1024
classLoadComplete @ loader.js:164
error (async)
loadScript @ loader.js:291
cheerpjLoadJarPackage @ loader.js:313
_m4VanRn3cGKuPdWarunFbsZWMJZK0ueWtrzeSNe9ZKebNxKp @ rt.jar.js:297
_m4VanRn3cGKuPdWarKnEbsZWMJZK0ueWtrzCmA0j1YINe9ZKebNxer @ rt.jar.js:324
_m4VanJm3cGKuPdabzjaMczqrpeSNe9h8mtteCEr1a @ rt.jar.js:324
_m4VanJm3cGKuPdabzjaMczqrpeSNe9h8mtteCEr1a @ rt.jar.js:324
_c4pbMxWAxsDjavJWbrKV2Zd3cGKuPdabzjaMczqrpeSNe9h8mtteCEr1a @ rt.jar.js:1776
loadWeakClass @ loader.js:339
cjG @ loader.js:2191
_c4pbQ3qZrZFa0mSqejHFmn9yxZvGVlpgon9W500qiqappkTbXek10d1e7uebaJ3RNb9xSnItTntza @ rt.jar.com.js:242
_c4pbQZDUHdrWs$aqfYaomrqqVveYeXMZaMNb9taRr2C400J7AjNttdHab8qS2M3l @ AnnotateModelJSON.jar.js:55
_c4pbQVDUHdrWs$aqfYaomrqa_pXfHa1eHxuFG8$kbefH00c9BCo3cGKKuQKm_kH0JtJeb @ AnnotateModelJSON.jar.js:55
_c4pbQRDUHdrWs$aqfYaomrqWoXfHa1eHxuEG8$kbefH00c9BCo3cGKKuQKm_kH0JtJeb @ AnnotateModelJSON.jar.js:55
_c4pbQFDUHdrWs$aqfYW$kbefH0epGKbXpS3RxuKKm_kH0JtJeb @ AnnotateModelJSON.jar.js:27
(anonymous) @ VM57637:3
runContinuationStack @ loader.js:374
cheerpjSchedule @ loader.js:1024
rt.jar.com.js:512 POST http://localhost:8084/AnnotateROIServer/webresources/ImageAnnotation 405 (Method Not Allowed)

**Comment by willishf** [comment]
In looking through the javascript API for doing a http GET,POST,PUT etc assuming using https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open where it appears the type needs to be set when the URL is open. The Java API has the connection.setRequestMethod("PUT") does not have a corresponding method in XMLHttpRequest.  Would seem that a call in Java to connection.setRequestMethod("PUT") would require creating a new XMLHttpRequest object. 

Trying to meet a demo deadline and currently stuck on the ability to send JSON to server via standard REST api.

**Comment by alexp-sssup** [comment]
This should be fixed in current "latest". Please remember to clear up the browser cache before testing to get new the code.

**Comment by willishf** [comment]
Was on vacation last week so just now testing. Improvement but still a problem. Get the following which appears to be related to processing the response. Looking at the server log getting the expected data to show up on server side but is posted three times which is in response to an error processing response. The Java code works as expected and server side code is standard REST libraries for JAX and Jersey frameworks. 

Not sure what I can do to facilitate testing or providing sample code. 

com.goebl.david.WebbException: java.io.FileNotFoundException: http://localhost:8084/AnnotateROIServer/webresources/ImageAnnotation
cheerpOS.js:1379 

cheerpj.js:1 assertion "
cheerpj.js:1 false
cheerpj.js:1 " failed: file "
cheerpj.js:1 CheerpJCompression.cpp
cheerpj.js:1 ", line 
cheerpj.js:1 354
cheerpj.js:1 static uint8_t CheerpJCompiler::CompressedState::getIdentifierBase64Value(char)

**Comment by alexp-sssup** [comment]
Make sure that there is no CORS issue. Is the web page hosted on the same domain as the application server? PUT requests need special permission in a cross domain setting. If that is not the problem we will need access to a sample to be able to understand this problem.

**Comment by willishf** [comment]
Same server/port and not getting a CORS problem. Server is processing the request and outputting the data that I am sending to JSON so that is working. The exception that is being thrown appears to be involved with processing the results.

**Comment by alexp-sssup** [comment]
Can you share the full HTTP answer including headers?

**Comment by willishf** [comment]
This is the server side method where response is void and suspect the problem is the void. Changed the server method to return "Hello" and it works as expected. For the call to getIdentifierBase64Value that threw the exception probably can't handle null or  shouldn't be called if null return case. 

    /**
     * PUT method for updating or creating an instance of ImageAnnotationResource
     * @param content representation for the resource
     */
    @PUT
    @Consumes(MediaType.APPLICATION_JSON)
    public void putJson(ImageAnnotation content) {
        
        System.out.println("putJson:" + content.getImageKey() + ":" + content.getAnnotator() + ":" + content.getPoints());
    }

**Comment by alexp-sssup** [comment]
The error message about ```getIdentifierBase64Value``` is internal, ignore it.

Can you share the actual HTTP response when the error happens? Not the server code, but the response sent including headers.

**Comment by willishf** [comment]
I don't have anything setup to capture the http traffic. Any suggestions besides dropping into low level code and writing out the data? Will see if I can capture data stream in Java.

**Comment by willishf** [comment]
For the Java code where returning the String "Hello" get the following 5 bytes that is hello which is expected.
readBytes length:5
0:72
1:101
2:108
3:108
4:111

Changing the REST call back to void get the following
readBytes length:0

This is readBytes code where a ByteArrayOutputStream with length 0 is being converted to a ByteArray. This is then followed by a cast handler where String.class is expected and a String is being converted with a byte array that is of length 0 or should be with a UTF designation for the byte array.  

    public static byte[] readBytes(InputStream is) throws IOException {
        if (is == null) {
            return null;
        }
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        
        copyStream(is, baos);
        System.out.println("readBytes length:" + baos.size());
        byte[] dummy = baos.toByteArray();
        for(int i = 0; i < dummy.length; i++){
            System.out.println(i + ":" + dummy[i]);
        }
        return baos.toByteArray();
    }


Code to convert the result to the appropriate response. 


        byte[] responseBody = WebbUtils.readBytes(responseBodyStream);
        // we are ignoring headers describing the content type of the response, instead
        // try to force the content based on the type the client is expecting it (clazz)
        if (clazz == String.class) {
            response.setBody(new String(responseBody, Const.UTF8));
        } else if (clazz == Const.BYTE_ARRAY_CLASS) {
            response.setBody(responseBody);
        } else if (clazz == JSONObject.class) {
            response.setBody(WebbUtils.toJsonObject(responseBody));
        } else if (clazz == JSONArray.class) {
            response.setBody(WebbUtils.toJsonArray(responseBody));
        }

**Comment by alexp-sssup** [comment]
You can see the whole HTTP answer including headers by using the Network tab of the dev tools in the browser.

**Comment by willishf** [comment]
Screen shot of headers in the case where return is void. The second image shows no data returned which is expected. I am suspecting the problems is related to a 0 length byte array being convereted to a String if you follow the code. Since I don't know where the exception is being thrown in Javascript don't have specifics. I can keep adding print debug statements to find the exact line it throws an exception. 

![image](https://user-images.githubusercontent.com/4054430/43991783-c0073184-9d41-11e8-8f39-0dd0b0f9638e.png)

![image](https://user-images.githubusercontent.com/4054430/43991792-dc2d9e2a-9d41-11e8-9cda-f10ea20111e2.png)

**Comment by alexp-sssup** [comment]
I think the problem is caused by the ```204 No Content``` HTTP status. It should be now properly supported. Please clear your browser cache and try again.

**Comment by willishf** [comment]
That appears to have fixed it. Thanks for the quick response.
