### ISSUE TITLE
java.nio.file.Path#toUri crashes

### ISSUE THREAD

**Issue by vonwenckstern** [leaningtech/cheerpj-meta#55]
I receive this error when loading a normal text file via classloader and URI resources.

```
loader.js:409 Uncaught ReferenceError: _c4pbMlaRcSt42fs20UnixNativeDispatcher5stat0EJmLIKeLc0FileAttributesEV is not defined
    at _c4pbMlaRcSZ32fs20UnixNativeDispatcher4statEmDsW8ezcXPathmXJKeXd0FileAttributesEV (rt.jar.sun.nio.fs.js:124)
    at _c4pbMlaRcSd32fs18UnixFileAttributes3getEmrsrJuCkW0XCtwq1o (rt.jar.sun.nio.fs.js:84)
    at _c4pbMlaRcSd22fs12UnixUriUtils5toUriEmbsW8e9rXPathEg0pbSs8T7Qi (rt.jar.sun.nio.fs.js:280)
    at N3sun3nio2fs8UnixPath._c4pbMlaRcSt12fs8UnixPath5toUriEVEg0pbSs8T7Qi (rt.jar.sun.nio.fs.js:206)
    at N11CRC275b7265._c4Vanln3kN9EEWUTEEoWZZcMhd9BmAqcHW0usa (eval at _c4pbMBWAD72ibuqytpquG0qO140GX4qjXTaij5Tq_bNxuedRTPXq_gJgKqimjLj (rt.jar.js:1875), <anonymous>:1:438)
    at N4java4util6stream21ReferencePipeline$3$1._i4pbNkWlcaVakdoJD9krbrerJarkYdXcsdH_TFToGGaXZKhd9JmAqcHWK3l (rt.jar.java.util.stream.js:229)
    at N4java4util29Spliterators$ArraySpliterator._i4pbN2P0Spliterators$ArraylfbKmx4e5biCSsWaGqaYb7TepfZxq1iuapkZ50irXqe59c (rt.jar.java.util.js:341)
    at N4java4util6stream19ReferencePipeline$3._i4pbNkWlcaVak3ntTUwG0ueGWukYdXcsdbVGZdMyZKJNuTumolsJYsejqZnZ$SGmrebm5e59c [as v15] (rt.jar.java.util.stream.js:958)
    at N4java4util6stream19ReferencePipeline$3._i4pbNkWlcaVakxotTUwG0ueGWukYdXcsdrDUveWJwZaNZdMyZKJNu1umolsJYsmjqZlZ$SGmrebm5eH1l [as v14] (rt.jar.java.util.stream.js:958)
    at _i4pbNkWlcaVak7mJn9NtKhGWb6JKFski50evaluateSequentialEsXJJoNI8qSG0qesS8qeTKxc08YSpliteratoriPdb2xm$RdYa (rt.jar.java.util.stream.js:381)
```

I am trying to figure out what may cause this error. Maybe you have any information so that I can give you a better test case. We are using cheerpJ 1.0 runtime version.

**Comment by vonwenckstern** [comment]
After adding many println in the Java code, I figured out that it crashes at `URI toUri();` for the `java.nio.file.Path`

**Comment by alexp-sssup** [comment]
This problem is fixed in CheerpJ 1.3

**Comment by vonwenckstern** [comment]
@alexp-sssup In the latest version this error also occurs (however the error message is slightly different).
I just used `<script src="https://cjrt.leaningtech.com/latest/loader.js"></script>` and deployed only the `ocl.jar` but no `ocl.jar.js` so that it uses the latest compiler.

```
loader.js:396 Uncaught ReferenceError: _c4pbMlaRcSJ42fs20UnixNativeDispatcher5stat0E35 is not defined
    at _c4pbMlaRcSt42fs20UnixNativeDispatcher4statE34 (rt.jar.sun.nio.fs.js:313)
    at _c4pbMlaRcSt32fs18UnixFileAttributes3getE1 (rt.jar.sun.nio.fs.js:478)
    at _c4pbMlaRcSt22fs12UnixUriUtils5toUriE2 (rt.jar.sun.nio.fs.js:472)
    at N3sun3nio2fs8UnixPath._c4pbMlaRcSt12fs8UnixPath5toUriE39 (rt.jar.sun.nio.fs.js:264)
    at _c4p52de9monticore2io5paths9ModelPathC2E0 (eval at <anonymous> (eval at buildContinuations (loader.js:115)), <anonymous>:1:1027)
    at _c4p52de9monticore2io5paths9ModelPathC2E1 (eval at <anonymous> (eval at buildContinuations (loader.js:115)), <anonymous>:1:2738)
    at Object.eval [as func] (eval at buildContinuations (loader.js:115), <anonymous>:3:371)
    at runContinuationStack (loader.js:382)
    at cheerpjSchedule (loader.js:1051)
    at HTMLScriptElement.classLoadComplete (loader.js:167)
```

![image](https://user-images.githubusercontent.com/30497492/50238061-ba8d4200-03be-11e9-8471-fa87287fe125.png)

**Comment by alexp-sssup** [comment]
Apologies, indeed the native UnixNativeDispatcher.stat0 method is not implemented yet. We will fix this.

**Comment by alexp-sssup** [comment]
The problem should be fixed in current "latest"

**Comment by vonwenckstern** [comment]
@alexp-sssup I tried it out today and it still does not work.
I used the JAR without providing the JavaScript file (cf. Screenshot below that it does not find the current JS file) so that I use the latest branch.

@alexp-sssup  Is there a way I can test it?

![image](https://user-images.githubusercontent.com/30497492/51334219-a43ada80-1a7f-11e9-9278-e08d6a289969.png)

Here is the output of the current test:
![image](https://user-images.githubusercontent.com/30497492/51333986-2971bf80-1a7f-11e9-95e6-9ef3462fd75f.png)

@alexp-sssup: Also sorry for my late answer (I knew I promised you to answer earlier, but I am on holiday -- I will be back on Tuesday; and then I will also try it with the new approach you answer this time to me).

**Comment by alexp-sssup** [comment]
Please clear your browser cache and try again.

**Comment by vonwenckstern** [comment]
@alexp-ssup: Yes this issue is solved if I clear everything xampp and Chrome.

But I still receive an error later (which does not occur running the JAR-CLI directly).
![image](https://user-images.githubusercontent.com/30497492/51476105-c89afd80-1d84-11e9-8eb7-4c8a6ea38b4f.png)

In the next days I will add debug information to figure out why it does not work.
@alexp-sssup: Thank you for your support.
